[package]
name = "node_editor"
version = "0.1.0"
edition = "2024"

[dependencies]
iced.workspace = true
iced.features = ["debug"]

iced_palace.workspace = true
iced_palace.features = ["geometry"]

function.workspace = true
